### ISSUE TITLE
networkx doesn't always like fork start method

### ISSUE THREAD

**Issue by jmon12** [ddelange/mapply#42] opened 2023-03-15 12:38 UTC
#### Description

My usecase is a few quite heavy operations, not a lot of cheap operations. Specifically, I have a dataframe of graph objects I'm applying some measures on. Therefore, the idea is to have _one worker per row_ (e.g. per graph), which translates in **`chunk_size = 1`** at the initialization step.

However, from the [documentation](https://mapply.readthedocs.io/en/stable/_code_reference/mapply.html#mapply.init), setting `chunk_size` to 1 has a different behavior:

> Set to 1 to let max_chunks_per_worker decide.

How can I force `mapply` to have one worker per row, e.g. a chunk size of 1?

#### Use case / motivation / context

I tried the following combinations of parameters, and in every case, only 1 worker is spawn:

 - `chunk_size=1` and `max_chunks_per_worker=10`
 - `chunk_size=1` and `max_chunks_per_worker=0` - Should ignore the max chunks check.
 - `chunk_size=1` and `max_chunks_per_worker=1` - This is the most surprising one: it should work since it constraints both to 1. Note that I have more CPU cores than rows for the df I'm testing on.

Let's take the following example, the `'graph'` column of some `DataFrame` `df` is populated with some `networkx.Graph` object, and let's apply [`networkx.diameter`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.distance_measures.diameter.html) to each one of them in parallel. Note that `len(df)` is smaller than the number of cores (anyway a detail).

Here is the actual code for the last case using `mapply` (spawning only one worker).

```python
import mapply

mapply.init(
    n_workers=-1,
    chunk_size=1,
    max_chunks_per_worker=1
)

df['diameter'] = df['graph'].mapply(lambda x: nx.diameter(x))
```

Note that other ways - namely natively with `multiprocessing` and with `pandarallel` work as expected, see the code below.

```python
import networkx as nx
import multiprocessing as mp

with mp.Pool(len(df)) as pool:
    df['diameter'] = pool.map(nx.diameter, df['graph'])
```

```python
from pandarallel import pandarallel

pandarallel.initialize()

df['diameter'] = df['graph'].parallel_apply(nx.diameter)
```

#### Environment

Apple hardware with Apple M1 Pro CPU (10 cores) with:
 - MacOS 12.6.3
 - Darwin Kernel Version 21.6.0
 - Virtualenvironment with
    - python 3.10.10
    - `mapply 0.1.21`
    - `pandarallel 1.6.4`
 - Run in a jupyter notebook from VSCode
    - `ipython 8.6.0`
    - VSCode 1.76.1

**Comment by jmon12** [comment] 2023-03-15 12:47
Note that using `chunk_size=2` works as expected. There is likely something with the special value of 1 and its purpose as specified in the doc.

**Comment by ddelange** [comment] 2023-03-15 12:50
Hi @jmon12 👋 

When you set `max_chunks_per_worker=0`, the check is disabled: https://github.com/ddelange/mapply/blob/0.1.21/src/mapply/mapply.py#L36-L38

And you can then use `chunk_size=1` to send one row to one worker (few lines above).

If you set `n_workers=1`, the amount of workers spawned is determined by the amount of cores you have, but never more than the amount of chunks: https://github.com/ddelange/mapply/blob/0.1.21/src/mapply/parallel.py#L55-L57

In the snippet below, you can see from the progress bar that 1000 chunks (1 chunk per row, `chunk_size=1`) are created (and so indeed `max_chunks_per_worker` functionality has been disabled):

```py
In [1]: import mapply
time: 92.1 ms (started: 2023-03-15 13:46:20 +01:00)

In [2]: mapply.init(max_chunks_per_worker=0, chunk_size=1)
time: 653 µs (started: 2023-03-15 13:46:38 +01:00)

In [3]: mapply.parallel.N_CORES  # I have a macbook with 8 logical (4 physical) cores
Out[3]: 5
time: 12.2 ms (started: 2023-03-15 13:47:00 +01:00)

In [4]: series = pd.Series(range(1000))
time: 960 µs (started: 2023-03-15 13:48:35 +01:00)

In [5]: series.mapply(lambda x: x**2)
100%|███████████████| 1000/1000 [00:07<00:00, 141.70it/s]
Out[7]:
0           0
1           1
2           4
3           9
4          16
        ...
995    990025
996    992016
997    994009
998    996004
999    998001
Length: 1000, dtype: int64
time: 7.33 s (started: 2023-03-15 13:48:37 +01:00)
```

**Comment by ddelange** [comment] 2023-03-15 12:55
> Note that using `chunk_size=2` works as expected. There is likely something with the special value of 1 and its purpose as specified in the doc.

note that this is the only line where `chunk_size` is used, nothing special about `chunk_size=1` in that sense: https://github.com/ddelange/mapply/blob/0.1.21/src/mapply/mapply.py#L32

**Comment by ddelange** [comment] 2023-03-15 12:59
How did you verify that only one worker is spawned? In my snippet above, these 1000 chunks seen in the progressbar are distributed across 5 forked subprocesses in the background. No matter the amount of workers, you only get to see a single progressbar: https://github.com/ddelange/mapply/blob/0.1.21/src/mapply/parallel.py#L103-L104

**Comment by ddelange** [comment] 2023-03-15 13:17
In your case (less rows than cores), you should be able to leave `max_chunks_per_worker` untouched, because `chunk_size=1` will not create more chunks than there are workers: so whatever value you have at `max_chunks_per_worker`, it won't affect behaviour on such a small df.

I'm now very curious :) What does `mapply.parallel.N_CORES` output on your system? You wrote it's a 10core ARM mac (meaning no hyperthreading, logical == physical cores), so the output here should be 10. If that is indeed the case, there definitely should be multiple subprocesses forked as soon as iteration over [`pool.imap`](https://github.com/ddelange/mapply/blob/0.1.21/src/mapply/parallel.py#L101) starts.

Can you set
```
import logging
logging.basicConfig(level=logging.DEBUG)

mapply.init(chunk_size=1)
```
and run the mapply again? It should output how many subprocesses are being forked.

**Comment by jmon12** [comment] 2023-03-15 14:07
Hi @ddelange !

Thank you for your quick and complete reply. Here some answers to your questions. Note that I restarted the jupyter kernel and used only `mapply` to avoid any kind of potential "interferences".

 - `N_CORES` is indeed 10 as it should
 - Note that I don't have any special input with `DEBUG` logging. I'm probably missing something.

Using `mapply.init(n_workers=-1, chunk_size=1, max_chunks_per_worker=0)`: the progress bar indeed shows 4 workers as it should (4 entries in the df), however `htop` shows only one simultaneous process at the time, and the running time is indeed the same or more than the sequential pure-pandas code.

I will test your more minimalistic example and come back to you. Maybe something else is going on in picking the function of an external library...

I'm of course available for any complementary information you might need! Let me know.

PS: That's actually why I'm interested in `mapply`: it uses `dill`. I had some troubles in parallelizing python code because of the limited native pickling process.

**Comment by ddelange** [comment] 2023-03-15 16:12
From what you describe, there should be 4 subprocesses running (but maybe not at 100%? could try the filter functionality of htop?). Can't imagine networkx doing some locking to prevent multiprocessing, why would they...

I just confirmed I see 5 subprocesses in `htop` with snippet:
```py
import pandas as pd
import mapply
mapply.init(chunk_size=1, max_chunks_per_worker=0)

def crunch(x):
    for _ in range(1000000):
        x ** 2

pd.Series(range(1000)).mapply(crunch)
```

**Comment by ddelange** [comment] 2023-03-19 09:32
by the way, if you don't need pandas per se, and just want to apply some fn(graph) to some graphs, you can also use the [parallel module](https://mapply.readthedocs.io/en/stable/_code_reference/mapply.html#module-mapply.parallel) directly

**Comment by jmon12** [comment] 2023-03-20 16:33
The both cases work as expected.

The only difference is that I'm using dedicated `pd.Series` object instead of indexing the dataframe... Here you have the code (with network creation preamble).

```python
# Creating the graphs
# N = 2^14 = 16384 and p such as E >~= N (similar to my case)
N = 1 << 14
p = 0.0001
graphs = pd.Series(range(6)).mapply(lambda x: nx.erdos_renyi_graph(N, p))

# Reduce to LCC to apply the diameter function (needs to be connected)
graphs = graphs.apply(max(nx.connected_components(x), key=len)).copy())

# Diameter measure
diameters = graphs.mapply(nx.diameter)
```

I don't know what could be the relevant difference between this and my usecase. I'll be testing again in my real case scenario. If you have any idea/suggestion let me know.

**Comment by ddelange** [comment] 2023-03-21 06:28
this last snippet you posted works? but your complex networkx code doesnt? that's super interesting, worth a deep dive into their code :)

another thing worth checking would be if your complex code works if the importing of that code only happens in the forked subprocess. if that starts to work, networkx doesn't like forking the main process (which doesn't require pickling of the state of your python objects at the point in time where you start the pool, in contrast to spawning which will create vanilla processes). mapply uses fork by default, because it's much faster to start up. for more info, see https://github.com/uqfoundation/pathos/issues/250#issuecomment-1271111349

**Comment by ddelange** [comment] 2023-03-21 06:33
no idea what they're doing in networkx but it seems indeed related to fork start method 🤔 https://github.com/networkx/networkx/issues/3168#issuecomment-425221102

can you try your complex example with:

```py
import mapply
import multiprocess
multiprocess.set_start_method('forkserver')
mapply.init(...)
```
?

**Comment by ddelange** [comment] 2023-04-10 19:25
Hi @jmon12 👋 did you figure out which method(s) of networkx might cause the bug? I would be interested in reporting it upstream :)

**Comment by ddelange** [comment] 2023-04-24 06:02
@jmon12 I'll close this as an upstream issue. If you find out which networkx method stops working, please let me know. The issue I linked above also talks about interference from importing sqlite3, which leads me to think this might have something to do with disk i/o and/or locks.

**Closed by ddelange** 2023-04-24 06:02 UTC
Labels: question
