### ISSUE TITLE
bug: lambda that uses imported functions

### ISSUE THREAD

**Issue by kasra-keshavarz** [ddelange/mapply#11] opened 2021-07-07 21:47 UTC
#### Description

Using imported functions

#### Use case / motivation

`mapply` only works with imported function when they are explicitly imported in the body of the function they are called. Take the following code for example:

```
from math import sqrt

import pandas as pd
import numpy as np

import mapply
mapply.init(
    n_workers=-1,
    chunk_size=1,
    max_chunks_per_worker=10,
    progressbar=False
)

df = pd.DataFrame(np.random.rand(500,5))
df.mapply(lambda x: sqrt(x), axis=0)
```

the code above results in an error that `sqrt`is not defined. It only works when the `import` statement is used within the lambda function.

#### Related Issues

Nothing comes to mind.

**Comment by ddelange** [comment] 2021-07-08 06:28
Hi @kasra-keshavarz,

Thanks for posting this issue, I'm glad you found a workaround.

I'm afraid this is most lilely a [downstream bug](https://github.com/uqfoundation/dill/issues?page=1&q=is%3Aissue+lambda+import) (although I'm not at my machine to confirm).

I agree that your example above looks like something you'd want to work, a general safe practise however would be to avoid lambdas for complex operations:

```py
from math import sqrt

df.mapply(sqrt, axis=0)

def cool_polynomial(x):
    """Putting more complex logic like this in a lambda quickly becomes unreadable."""
    return sqrt(x) + 1

df.mapply(cool_polynomial, axis=0)
```

Hope that helps!

**Comment by thoughtfuldata** [comment] 2021-11-05 05:59
I just ran into this bug. can confirm that importing inside the lambda function works

**Comment by ddelange** [comment] 2021-11-05 06:11
```pycon
>>> from math import sqrt
... 
... import pandas as pd
... import numpy as np
... import mapply
... 
... mapply.init(progressbar=False)
... 
... df = pd.DataFrame(np.random.rand(500))
... df.mapply(lambda x: sqrt(x), axis=1)
0      0.649900
1      0.653619
2      0.910843
3      0.901363
4      0.955056
         ...
495    0.448268
496    0.696137
497    0.786392
498    0.833481
499    0.980583
Length: 500, dtype: float64

>>> from packaging.markers import default_environment
>>> default_environment()
{'implementation_name': 'cpython', 'implementation_version': '3.8.10', 'os_name': 'posix', 'platform_machine': 'x86_64', 'platform_release': '19.6.0', 'platform_system': 'Darwin', 'platform_version': 'Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64', 'python_full_version': '3.8.10', 'platform_python_implementation': 'CPython', 'python_version': '3.8', 'sys_platform': 'darwin'}
```

On my system the MWE works as expected. Can you provide more details about your system and the traceback you receive?

**Comment by thoughtfuldata** [comment] 2021-11-05 18:06
`temp_df['transcripts'] = temp_df.mapply(get_transcripts, axis=1)`

the above call wont work, unless `import youtube_transcript_api as yta` is inside the custom function

```
import requests as rq

import numpy as np
import pandas as pd

import youtube_transcript_api as yta


def get_transcripts(video_id):

    try:
        print(video_id[0], video_id)
        transcripts = yta.YouTubeTranscriptApi.get_transcript(
            video_id[0], cookies='cookies/cookies.Youtube.txt')
        return transcripts

```

**Comment by ddelange** [comment] 2021-11-06 14:19
The 'not defined' error does not occur for me when [using an imported namespace or function in a lambda](https://colab.research.google.com/drive/1SYSNyV0UJldFLepNKPSHVLm8K2v4ZaqJ?usp=sharing) neither on my Mac nor on Linux (Google Colab). My hunch is that this is a Windows specific pickling issue. I would suggest creating an issue in the dill repository with a reproducible script (and traceback) that demonstrates this behaviour on Windows.

If your issue gets resolved upstream, please report back here!

**Comment by ma7555** [comment] 2022-02-11 15:51
> 

yes I am on Windows.

**Comment by ddelange** [comment] 2022-02-11 19:13
in that case, this issue might be related: https://github.com/uqfoundation/dill/issues/323

as a fix was merged for it, you could try upgrading dill to the latest version with `pip install -U dill`

**Comment by ddelange** [comment] 2022-02-11 19:17
Closing as duplicate of https://github.com/uqfoundation/multiprocess/issues/58

**Closed by ddelange** 2022-02-11 19:17 UTC
Labels: bug
